/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ideia;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stefano
 */
public class GUIIdeia extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(GUIIdeia.class.getName());
    
    public GUIIdeia() {
        initComponents();
        setVisible(true);
        consultar();
    }

    public void addListener(GerenciadorIdeia gi) {
        JBTenviar.addActionListener(gi);
        JBTlimpar.addActionListener(gi);
    }

    // Cria uma Ideia com base nos campos da tela
    public Ideia getIdeia(String autor) {
        String titulo = JTFtitulo.getText();
        String descricao = JTFdescricao.getText();
        Ideia i = new Ideia(titulo, descricao);
        // se uma linha estiver selecionada, usa o id para alteração
        int sel = jTable1.getSelectedRow();
        if (sel != -1) {
            Object val = jTable1.getModel().getValueAt(sel, 0); // coluna 0 = ide_id (oculta)
            if (val instanceof Integer) i.setIdeId((Integer) val);
            else if (val instanceof Number) i.setIdeId(((Number) val).intValue());
            else {
                try { i.setIdeId(Integer.parseInt(String.valueOf(val))); } catch (Exception ex) { /* ignore */ }
            }
        }
        return i;
    }
                                    
                                         

    // Botão Limpar
    public void limpar() {                                         
            JTFtitulo.setText("");
            JTFdescricao.setText("");
            JTFdescricao1.setText("");
            jTable1.clearSelection();
    } 
    
    // Carrega as ideias do banco na tabela
public void consultar() {
    try {
        DAOIdeia dao = new DAOIdeia();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        java.util.List<Ideia> lista = dao.listar();
        model.setRowCount(0);
        for (Ideia it : lista) {
            String autor = "";
            if (it.getAdmId() != null) autor = "Administrador:" + it.getAdmId();
            else if (it.getVolId() != null) autor = "Voluntário:" + it.getVolId();
            else if (it.getExtId() != null) autor = "Externo:" + it.getExtId();
            model.addRow(new Object[]{
                it.getIdeTitulo(),
                it.getIdeConteudo(),
                autor
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, e, "Erro!", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    // Retorna id da ideia selecionada (0 se nada selecionado)
    public int getIdIdeia() {
        int sel = jTable1.getSelectedRow();
        if (sel == -1) return 0;
        Object val = jTable1.getModel().getValueAt(sel, 0);
        if (val instanceof Integer) return (Integer) val;
        if (val instanceof Number) return ((Number) val).intValue();
        try { return Integer.parseInt(String.valueOf(val)); } catch (Exception ex) { return 0; }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTenviar = new javax.swing.JButton();
        JBTlimpar = new javax.swing.JButton();
        JLtitulo = new javax.swing.JLabel();
        JLnome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        JLid = new javax.swing.JLabel();
        JLtitulo1 = new javax.swing.JLabel();
        JTFtitulo = new javax.swing.JTextField();
        JTFdescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JLnome1 = new javax.swing.JLabel();
        JTFdescricao1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JBTenviar.setBackground(new java.awt.Color(255, 102, 102));
        JBTenviar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        JBTenviar.setForeground(new java.awt.Color(255, 255, 255));
        JBTenviar.setText("Enviar");
        JBTenviar.setName("cadastrar"); // NOI18N
        JBTenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTenviarActionPerformed(evt);
            }
        });

        JBTlimpar.setBackground(new java.awt.Color(255, 0, 51));
        JBTlimpar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        JBTlimpar.setForeground(new java.awt.Color(255, 255, 255));
        JBTlimpar.setText("Limpar");
        JBTlimpar.setName("limpar"); // NOI18N
        JBTlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTlimparActionPerformed(evt);
            }
        });

        JLtitulo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(102, 0, 102));

        JLnome.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLnome.setForeground(new java.awt.Color(102, 0, 102));
        JLnome.setText("Descrição");

        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("French Script MT", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sugestão de Ideias");
        jLabel4.setMinimumSize(new java.awt.Dimension(146, 50));

        JLid.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLid.setForeground(new java.awt.Color(102, 0, 102));
        JLid.setText("Titulo:");

        JLtitulo1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        JLtitulo1.setForeground(new java.awt.Color(102, 0, 102));
        JLtitulo1.setText("Descreva sua ideia");

        JTFtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtituloActionPerformed(evt);
            }
        });

        JTFdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdescricaoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Descrição", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        JLnome1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        JLnome1.setForeground(new java.awt.Color(102, 0, 102));
        JLnome1.setText("Número de Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLnome)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JTFtitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFdescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(JBTlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                    .addComponent(JBTenviar))
                                .addComponent(JLnome1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFdescricao1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(JLtitulo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLid)
                            .addComponent(JLtitulo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLtitulo1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLtitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JLid, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(JTFtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(JLnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(JLnome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFdescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTenviar)
                    .addComponent(JBTlimpar))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTlimparActionPerformed
        // deixado vazio pois Gerenciador trata ações
    }//GEN-LAST:event_JBTlimparActionPerformed

    private void JBTenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTenviarActionPerformed
        // deixado vazio pois Gerenciador trata ações
    }//GEN-LAST:event_JBTenviarActionPerformed

    private void JTFtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFtituloActionPerformed

    private void JTFdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdescricaoActionPerformed

    private void JTFcodigoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcodigoAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcodigoAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIIdeia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTenviar;
    private javax.swing.JButton JBTlimpar;
    private javax.swing.JLabel JLid;
    private javax.swing.JLabel JLnome;
    private javax.swing.JLabel JLnome1;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JLabel JLtitulo1;
    private javax.swing.JTextField JTFdescricao;
    private javax.swing.JTextField JTFdescricao1;
    private javax.swing.JTextField JTFtitulo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    // Método para obter código do autor
    public String getCodigoAutor() {
        return JTFdescricao1.getText();
    }

    // Retorna o botão Enviar
    public javax.swing.JButton JBTenviar() {
        return JBTenviar;
    }

    // Retorna o botão Limpar
    public javax.swing.JButton JBTlimpar() {
        return JBTlimpar;
    }
}
